const SUPABASE_URL='https://usggjqukcqzttrilgmmo.supabase.co';
const SUPABASE_KEY='sb_publishable_g3Hi1tMxV4sV5bYXBpijBA_nHFd0zxA';
const API=`${SUPABASE_URL}/rest/v1`;
const $=s=>document.querySelector(s);
const prices=$('#prices'),search=$('#search'),modal=$('#modal'),statusBox=$('#dbStatus'),adminPanel=$('#adminPanel'),adminModal=$('#adminModal');
const tg=window.Telegram?.WebApp||null;
if(tg){tg.ready();tg.expand();}
let visitorId=(tg?.initDataUnsafe?.user?.id?String(tg.initDataUnsafe.user.id):localStorage.getItem('averagePriceVisitorId'))||crypto.randomUUID();
localStorage.setItem('averagePriceVisitorId',visitorId);
let items=[],myPrices=JSON.parse(localStorage.getItem('myPriceVotes')||'{}'),adminCode=sessionStorage.getItem('averagePriceAdminCode')||'',lang=localStorage.getItem('averagePriceLang')||'uk';
const T={uk:{connecting:'Підключення',loading:'Завантаження спільної бази…',connected:'Спільна база підключена',search:'Пошук позиції...',suggest:'+ Запропонувати',empty:'Нічого не знайдено.',sent:'Заявку відправлено адміністратору.',sendError:'Не вдалося відправити заявку. Спробуйте ще раз.',saveError:'Не вдалося зберегти ціну. Спробуйте ще раз.',adminSession:'Сесія адміністратора завершена.',adminAction:'Не вдалося виконати дію. Перевірте сесію адміністратора.',adminAddError:'Не вдалося додати позицію. Перевірте сесію адміністратора.',wrongCode:'Невірний код адміністратора.',dbError:'Помилка підключення до бази. Перевірте зʼєднання та перезавантажте сторінку.',votes:'голосів',mine:'Ваша ціна',average:'Середня ціна',yourPrice:'Ваша ціна',lower:'− 10 грн',higher:'+ 10 грн',request:'Заявка',accept:'Додати в прайс',reject:'Відхилити'},en:{connecting:'Connection',loading:'Connecting to shared database…',connected:'Shared database connected',search:'Search position...',suggest:'+ Suggest',empty:'Nothing found.',sent:'Request sent to administrator.',sendError:'Could not send the request. Please try again.',saveError:'Could not save the price. Please try again.',adminSession:'Administrator session expired.',adminAction:'Could not complete the action. Check the administrator session.',adminAddError:'Could not add the position. Check the administrator session.',wrongCode:'Invalid administrator code.',dbError:'Database connection error. Check your connection and reload the page.',votes:'votes',mine:'Your price',average:'Average price',yourPrice:'Your price',lower:'− 10 UAH',higher:'+ 10 UAH',request:'Request',accept:'Add to price list',reject:'Reject'}};
const tr=k=>T[lang]?.[k]||T.uk[k]||k;
function headers(){return{apikey:SUPABASE_KEY,'Content-Type':'application/json'}}
async function rpc(name,body){const r=await fetch(`${API}/rpc/${name}`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return new Intl.NumberFormat(lang==='uk'?'uk-UA':'en-US').format(Math.round(Number(n)||0))}
function setStatus(text,ok){statusBox.innerHTML=`<strong>${ok?tr('connected'):tr('connecting')}</strong><span>${esc(text)}</span>`;statusBox.classList.toggle('ok',!!ok)}
async function loadItems(){setStatus(tr('loading'),false);try{const rows=await rpc('get_price_list',{p_telegram_user_id:visitorId});items=(rows||[]).map(x=>({...x,average_price:Number(x.average_price)||0,votes_count:Number(x.votes_count)||0}));setStatus(tr('connected'),true);render()}catch(e){console.error('PRICE LIST ERROR',e);setStatus(tr('dbError'),false)}}
function render(){const q=search.value.trim().toLowerCase(),list=items.filter(x=>String(x.name).toLowerCase().includes(q));prices.innerHTML='';$('#empty').classList.toggle('hidden',list.length>0);for(const x of list){const mine=Number.isFinite(myPrices[x.id])?myPrices[x.id]:null;const value=mine??(x.average_price||10);const avg=x.average_price||0;const pct=Math.max(1,Math.min(100,avg/5000*100));const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="cardHead"><div><h2>${esc(x.name)}</h2>${x.category||x.unit?`<div class="meta">${esc([x.category,x.unit].filter(Boolean).join(' · '))}</div>`:''}</div><span class="votes">${x.votes_count} ${tr('votes')}</span></div><div class="stats"><div><div class="label">${tr('mine')}</div><div class="value" data-my-value="${x.id}">${mine==null?'—':money(mine)+' UAH'}</div></div><div><div class="label">${tr('average')}</div><div class="value">${x.votes_count?money(avg)+' UAH':'—'}</div></div></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="sliderRow"><span>10</span><input class="priceSlider" data-id="${x.id}" type="range" min="10" max="5000" step="10" value="${value}"><span>5000</span></div><div class="sliderCurrent"><span>${tr('yourPrice')}</span><b data-slider-value="${x.id}">${money(value)} UAH</b></div><div class="cardActions"><button data-id="${x.id}" data-action="lower">${tr('lower')}</button><button data-id="${x.id}" data-action="higher">${tr('higher')}</button></div>`;prices.appendChild(el)}}
async function savePrice(id,value){value=Math.max(10,Math.min(5000,Math.round(Number(value)/10)*10));try{await rpc('submit_price_vote',{p_item_id:id,p_telegram_user_id:visitorId,p_price:value});myPrices[id]=value;localStorage.setItem('myPriceVotes',JSON.stringify(myPrices));await loadItems()}catch(e){console.error('SAVE PRICE ERROR',e);setStatus(tr('saveError'),false)}}
prices.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id,x=items.find(i=>i.id===id);if(!x)return;const cur=Number.isFinite(myPrices[id])?myPrices[id]:(x.average_price||10);savePrice(id,cur+(b.dataset.action==='higher'?10:-10))});
prices.addEventListener('input',e=>{const s=e.target.closest('.priceSlider');if(!s)return;const c=s.closest('.card'),id=s.dataset.id,v=Number(s.value);c.querySelector(`[data-slider-value="${id}"]`).textContent=`${money(v)} UAH`;c.querySelector(`[data-my-value="${id}"]`).textContent=`${money(v)} UAH`});
prices.addEventListener('change',e=>{const s=e.target.closest('.priceSlider');if(s)savePrice(s.dataset.id,s.value)});
$('#addBtn').onclick=()=>modal.showModal();
$('#suggestForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#suggestName').value.trim();if(name.length<2)return;const btn=e.target.querySelector('.primary');if(btn){btn.disabled=true;btn.textContent='Відправлення…'}try{await rpc('submit_price_suggestion',{p_text:name,p_telegram_user_id:visitorId});e.target.reset();modal.close();setStatus(tr('sent'),true)}catch(err){console.error('SUGGEST ERROR',err);setStatus(tr('sendError'),false)}finally{if(btn){btn.disabled=false;btn.textContent='Відправити заявку'}}});
$('#adminBtn').onclick=()=>{if(adminCode){adminPanel.classList.remove('hidden');loadAdminSuggestions();adminPanel.scrollIntoView({behavior:'smooth'})}else adminModal.showModal()};
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const code=$('#adminCode').value.trim();try{await rpc('admin_list_price_suggestions',{p_admin_code:code});adminCode=code;sessionStorage.setItem('averagePriceAdminCode',code);adminModal.close();adminPanel.classList.remove('hidden');await loadAdminSuggestions();adminPanel.scrollIntoView({behavior:'smooth'})}catch(err){console.error(err);alert(tr('wrongCode'))}});
async function loadAdminSuggestions(){if(!adminCode)return;const list=$('#adminList'),empty=$('#adminEmpty');try{const data=await rpc('admin_list_price_suggestions',{p_admin_code:adminCode});list.innerHTML='';empty.classList.toggle('hidden',!!data?.length);(data||[]).forEach(s=>{const el=document.createElement('div');el.className='request';el.innerHTML=`<div><b>${esc(s.text)}</b><div class="requestMeta">${tr('request')} · ${new Date(s.created_at).toLocaleString(lang==='uk'?'uk-UA':'en-US')}</div></div><div class="requestActions"><button class="accept" data-id="${s.id}">${tr('accept')}</button><button class="reject" data-id="${s.id}">${tr('reject')}</button></div>`;list.appendChild(el)})}catch(e){adminCode='';sessionStorage.removeItem('averagePriceAdminCode');adminPanel.classList.add('hidden');alert(tr('adminSession'))}}
$('#adminRefresh').onclick=loadAdminSuggestions;
$('#adminList').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.classList.contains('accept'))await rpc('admin_accept_price_suggestion',{p_admin_code:adminCode,p_suggestion_id:b.dataset.id});else await rpc('admin_reject_price_suggestion',{p_admin_code:adminCode,p_suggestion_id:b.dataset.id});await loadAdminSuggestions();await loadItems()}catch(err){console.error(err);alert(tr('adminAction'))}});
$('#adminAddBtn').onclick=async()=>{const name=$('#adminName').value.trim();if(name.length<2)return;try{await rpc('admin_add_price_item',{p_admin_code:adminCode,p_name:name,p_category:$('#adminCategory').value.trim()||null,p_unit:$('#adminUnit').value.trim()||null});$('#adminName').value='';$('#adminCategory').value='';$('#adminUnit').value='';await loadItems();await loadAdminSuggestions()}catch(e){console.error(e);alert(tr('adminAddError'))}};
search.addEventListener('input',render);
document.querySelectorAll('.langBtn').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('averagePriceLang',lang);document.documentElement.lang=lang;search.placeholder=tr('search');render()});
search.placeholder=tr('search');
loadItems();
if(adminCode){adminPanel.classList.remove('hidden');loadAdminSuggestions()}
