const SUPABASE_URL='https://usggjqukcqzttrilgmmo.supabase.co';
const SUPABASE_KEY='sb_publishable_g3Hi1tMxV4sV5bYXBpijBA_nHFd0zxA';
const API=`${SUPABASE_URL}/rest/v1`;
const PRICE_API=`${SUPABASE_URL}/functions/v1/price-api`;
const $=s=>document.querySelector(s);
const prices=$('#prices'),search=$('#search'),modal=$('#modal'),statusBox=$('#dbStatus'),adminPanel=$('#adminPanel');
const tg=window.Telegram?.WebApp||null;
if(tg){tg.ready();tg.expand();}
const visitorId=(tg?.initDataUnsafe?.user?.id?String(tg.initDataUnsafe.user.id):localStorage.getItem('averagePriceVisitorId'))||crypto.randomUUID();
localStorage.setItem('averagePriceVisitorId',visitorId);
const ADMIN_ID='1454798203';
const isAdmin=visitorId===ADMIN_ID;
let items=[],myPrices=JSON.parse(localStorage.getItem('myPriceVotes')||'{}'),lang='uk';
const T={uk:{appTitle:'Ціни від монтажників',eyebrow:'Колективний прайс монтажників України',subtitle:'Вкажіть свою ціну — система покаже середню ціну по всій групі.',connecting:'Підключення',loading:'Завантаження спільної бази…',connected:'Спільна база підключена',search:'Пошук позиції...',suggest:'+ Запропонувати',empty:'Нічого не знайдено.',sent:'Заявку відправлено адміністратору.',sendError:'Не вдалося відправити заявку. Спробуйте ще раз.',saveError:'Не вдалося зберегти ціну. Спробуйте ще раз.',adminAction:'Не вдалося виконати дію.',adminAddError:'Не вдалося додати позицію.',adminDeleteError:'Не вдалося видалити позицію.',votes:'голосів',mine:'Ваша ціна',average:'Середня ціна',yourPrice:'Ваша ціна',lower:'− 10 грн',higher:'+ 10 грн',request:'Заявка',accept:'Додати в прайс',reject:'Відхилити',anonymousTitle:'Анонімно для інших',anonymousText:'Інші учасники бачать лише середню ціну, а не вашу конкретну ціну.',cabinet:'Кабінет',requestsTitle:'Заявки на нові позиції',refresh:'Оновити',noRequests:'Нових заявок немає.',manualAdd:'Додати позицію вручну',positionName:'Назва профілю / полотна',category:'Категорія (необов’язково)',unit:'Одиниця (необов’язково)',addToPrice:'Додати в прайс',admin:'Адміністратор',footer:'Прайс монтажників України',suggestTitle:'Запропонувати позицію',suggestHint:'Напишіть профіль, полотно або іншу позицію, яку варто додати в колективний прайс. Після перевірки адміністратора вона з’явиться для голосування.',positionLabel:'Назва позиції',example:'Напр. Профіль ПВХ',suggestPriceLabel:'Ваша ціна, грн',sendRequest:'Відправити заявку',managePrice:'Керування прайсом',delete:'Видалити',deleteConfirm:'Видалити цю позицію з прайсу? Вона зникне для всіх учасників.',noItems:'Позицій немає.'}};
const tr=k=>T.uk[k]||k;
const displayName=x=>String(x.name);
const displayCategory=x=>String(x.category||'');
const displayUnit=x=>String(x.unit||'');
function applyLanguage(){document.documentElement.lang='uk';document.title=tr('appTitle');search.placeholder=tr('search');const p=$('#suggestPrice');if(p)p.placeholder='Напр. 250';const n=$('#suggestName');if(n)n.placeholder=tr('example')}
function headers(){return{apikey:SUPABASE_KEY,'Content-Type':'application/json'}}
async function rpc(name,body){const r=await fetch(`${API}/rpc/${name}`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
async function priceApi(action,body={}){const r=await fetch(PRICE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body,p_telegram_user_id:visitorId,initData:tg?.initData||''})});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return new Intl.NumberFormat('uk-UA').format(Math.round(Number(n)||0))}
function setStatus(text,ok){statusBox.innerHTML=`<strong>${ok?tr('connected'):tr('connecting')}</strong><span>${esc(text)}</span>`;statusBox.classList.toggle('ok',!!ok)}
async function loadItems(){setStatus(tr('loading'),false);try{const rows=await rpc('get_price_list',{p_telegram_user_id:visitorId});items=(rows||[]).map(x=>({...x,average_price:Number(x.average_price)||0,votes_count:Number(x.votes_count)||0,my_price:Number(x.my_price)||0}));for(const x of items){if(x.my_price>0)myPrices[x.id]=x.my_price}localStorage.setItem('myPriceVotes',JSON.stringify(myPrices));setStatus(tr('connected'),true);render();if(isAdmin)renderAdminItems()}catch(e){console.error('PRICE LIST ERROR',e);setStatus('Помилка підключення до бази. Перезавантажте сторінку.',false)}}
function render(){const q=search.value.trim().toLowerCase(),list=items.filter(x=>displayName(x).toLowerCase().includes(q)||displayCategory(x).toLowerCase().includes(q));prices.innerHTML='';$('#empty').classList.toggle('hidden',list.length>0);for(const x of list){const mine=Number.isFinite(myPrices[x.id])?myPrices[x.id]:(x.my_price>0?x.my_price:null);const value=mine??(x.average_price||10);const avg=x.average_price||0;const pct=Math.max(1,Math.min(100,avg/5000*100));const el=document.createElement('article');el.className='card';const meta=[displayCategory(x),displayUnit(x)].filter(Boolean).join(' · ');el.innerHTML=`<div class="cardHead"><div><h2>${esc(displayName(x))}</h2>${meta?`<div class="meta">${esc(meta)}</div>`:''}</div><span class="votes">${x.votes_count} ${tr('votes')}</span></div><div class="stats"><div><div class="label">${tr('mine')}</div><div class="value" data-my-value="${x.id}">${mine==null?'—':money(mine)+' грн'}</div></div><div><div class="label">${tr('average')}</div><div class="value">${x.votes_count?money(avg)+' грн':'—'}</div></div></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="sliderRow"><span>10</span><input class="priceSlider" data-id="${x.id}" type="range" min="10" max="5000" step="10" value="${value}"><span>5000</span></div><div class="sliderCurrent"><span>${tr('yourPrice')}</span><b data-slider-value="${x.id}">${money(value)} грн</b></div><div class="cardActions"><button type="button" data-id="${x.id}" data-action="lower">${tr('lower')}</button><button type="button" data-id="${x.id}" data-action="higher">${tr('higher')}</button></div>`;prices.appendChild(el)}}
function renderAdminItems(){if(!isAdmin)return;const list=$('#adminItemsList'),empty=$('#adminItemsEmpty');if(!list||!empty)return;list.innerHTML='';empty.classList.toggle('hidden',items.length>0);for(const x of items){const el=document.createElement('div');el.className='adminItem';const meta=[displayCategory(x),displayUnit(x),`${x.votes_count||0} ${tr('votes')}`].filter(Boolean).join(' · ');el.innerHTML=`<div><div class="adminItemName">${esc(displayName(x))}</div><div class="adminItemMeta">${esc(meta)}</div></div><button type="button" class="deleteItem" data-id="${x.id}">${tr('delete')}</button>`;list.appendChild(el)}}
async function savePrice(id,value){value=Math.max(10,Math.min(5000,Math.round(Number(value)/10)*10));try{await rpc('submit_price_vote',{p_item_id:id,p_telegram_user_id:visitorId,p_price:value});myPrices[id]=value;localStorage.setItem('myPriceVotes',JSON.stringify(myPrices));await loadItems()}catch(e){console.error('SAVE PRICE ERROR',e);setStatus(tr('saveError'),false)}}
prices.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id,x=items.find(i=>i.id===id);if(!x)return;const cur=Number.isFinite(myPrices[id])?myPrices[id]:(x.average_price||10);savePrice(id,cur+(b.dataset.action==='higher'?10:-10))});
prices.addEventListener('input',e=>{const s=e.target.closest('.priceSlider');if(!s)return;const c=s.closest('.card'),id=s.dataset.id,v=Number(s.value);c.querySelector(`[data-slider-value="${id}"]`).textContent=`${money(v)} грн`;c.querySelector(`[data-my-value="${id}"]`).textContent=`${money(v)} грн`});
prices.addEventListener('change',e=>{const s=e.target.closest('.priceSlider');if(s)savePrice(s.dataset.id,s.value)});
$('#addBtn').onclick=()=>modal.showModal();
const suggestForm=$('#suggestForm');
suggestForm.addEventListener('submit',async e=>{e.preventDefault();const name=$('#suggestName').value.trim();const price=Number($('#suggestPrice')?.value);if(name.length<2||!Number.isInteger(price)||price<10||price>5000||price%10!==0){setStatus('Вкажіть назву та ціну від 10 до 5000 грн з кроком 10 грн.',false);return}const btn=e.target.querySelector('.primary');if(btn){btn.disabled=true;btn.textContent='Відправлення…'}try{await priceApi('suggest',{text:name,price});e.target.reset();modal.close();setStatus(tr('sent'),true)}catch(err){console.error('SUGGEST ERROR',err);setStatus(tr('sendError'),false)}finally{if(btn){btn.disabled=false;btn.textContent=tr('sendRequest')}}});
const adminBtn=$('#adminBtn');
if(adminBtn&&!isAdmin)adminBtn.style.display='none';
if(adminBtn&&isAdmin){adminBtn.style.display='inline-flex';adminBtn.onclick=()=>{adminPanel.classList.remove('hidden');loadAdminSuggestions();renderAdminItems();adminPanel.scrollIntoView({behavior:'smooth'})}};
async function loadAdminSuggestions(){if(!isAdmin)return;const list=$('#adminList'),empty=$('#adminEmpty');try{const data=await rpc('admin_list_price_suggestions',{p_admin_code:visitorId});list.innerHTML='';empty.classList.toggle('hidden',!!data?.length);(data||[]).forEach(s=>{const el=document.createElement('div');el.className='request';el.innerHTML=`<div><b>${esc(s.text)}</b><div class="requestMeta">${tr('request')} · ${s.proposed_price?money(s.proposed_price)+' грн · ':''}${new Date(s.created_at).toLocaleString('uk-UA')}</div></div><div class="requestActions"><button type="button" class="accept" data-id="${s.id}">${tr('accept')}</button><button type="button" class="reject" data-id="${s.id}">${tr('reject')}</button></div>`;list.appendChild(el)})}catch(e){console.error('ADMIN LIST ERROR',e);alert(tr('adminAction'))}}
$('#adminRefresh').onclick=()=>{if(isAdmin){loadAdminSuggestions();loadItems()}};
$('#adminList').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||!isAdmin)return;try{if(b.classList.contains('accept'))await rpc('admin_accept_price_suggestion',{p_admin_code:visitorId,p_suggestion_id:b.dataset.id});else await rpc('admin_reject_price_suggestion',{p_admin_code:visitorId,p_suggestion_id:b.dataset.id});await loadAdminSuggestions();await loadItems()}catch(err){console.error(err);alert(tr('adminAction'))}});
$('#adminItemsList').addEventListener('click',async e=>{const b=e.target.closest('.deleteItem');if(!b||!isAdmin)return;const item=items.find(x=>x.id===b.dataset.id);if(!item)return;if(!confirm(`${tr('deleteConfirm')}\n\n${item.name}`))return;b.disabled=true;try{const ok=await rpc('admin_delete_price_item',{p_admin_code:visitorId,p_item_id:b.dataset.id});if(!ok)throw new Error('Delete failed');await loadItems();await loadAdminSuggestions()}catch(err){console.error('ADMIN DELETE ERROR',err);alert(tr('adminDeleteError'))}finally{b.disabled=false}});
$('#adminAddBtn').onclick=async()=>{if(!isAdmin)return;const name=$('#adminName').value.trim();if(name.length<2)return;try{await rpc('admin_add_price_item',{p_admin_code:visitorId,p_name:name,p_category:$('#adminCategory').value.trim()||null,p_unit:$('#adminUnit').value.trim()||null});$('#adminName').value='';$('#adminCategory').value='';$('#adminUnit').value='';await loadItems();await loadAdminSuggestions()}catch(e){console.error(e);alert(tr('adminAddError'))}};
search.addEventListener('input',render);
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});
document.addEventListener('dblclick',e=>{if(e.target.closest('button,input[type="range"],.priceSlider'))e.preventDefault()},{passive:false});
document.addEventListener('touchstart',e=>{if(e.touches.length>1)e.preventDefault()},{passive:false});
applyLanguage();loadItems();