const SUPABASE_URL='https://usggjqukcqzttrilgmmo.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZ2dqcXVrY3F6dHRyaWxnbW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1OTcyNDYsImV4cCI6MjEwMzE3MzI0Nn0.Y6-TW3GYRxycTUJZN4ARjVmJG0qm2sPWywnh2UhM4Vo';
const API=`${SUPABASE_URL}/rest/v1`, RPC=`${API}/rpc`;
const $=s=>document.querySelector(s);
const prices=$('#prices'),search=$('#search'),modal=$('#modal'),statusBox=$('#dbStatus'),adminPanel=$('#adminPanel'),adminModal=$('#adminModal');
let items=[]; let myPrices=JSON.parse(localStorage.getItem('myPriceVotes')||'{}');
const visitorId=localStorage.getItem('averagePriceVisitorId')||crypto.randomUUID(); localStorage.setItem('averagePriceVisitorId',visitorId);
let adminCode=sessionStorage.getItem('averagePriceAdminCode')||'';
function headers(extra={}){return {apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(extra||{})}}
async function api(path,opts={}){const r=await fetch(`${API}/${path}`,{...opts,headers:headers(opts.headers)});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
async function rpc(name,body){return api(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return new Intl.NumberFormat('uk-UA').format(Math.round(n))}
function setStatus(text,ok){statusBox.innerHTML=`<strong>${ok?'Спільна база':'Підключення'}</strong><span>${esc(text)}</span>`;statusBox.classList.toggle('ok',!!ok)}
async function loadItems(){setStatus('Завантаження спільної бази…',false);items=await api('price_item_stats?select=id,name,category,unit,is_active,average_price,votes_count&is_active=eq.true&order=name.asc')||[];setStatus('Спільна база підключена',true);render()}
function render(){const q=search.value.trim().toLowerCase();const list=items.filter(x=>x.name.toLowerCase().includes(q));prices.innerHTML='';$('#empty').classList.toggle('hidden',list.length>0);list.forEach(x=>{const mine=Number.isFinite(myPrices[x.id])?myPrices[x.id]:null, value=mine??x.average_price??10, avg=x.average_price||0,pct=Math.max(1,Math.min(100,avg/5000*100));const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="cardHead"><div><h2>${esc(x.name)}</h2>${x.category||x.unit?`<div class="meta">${esc([x.category,x.unit].filter(Boolean).join(' · '))}</div>`:''}</div><span class="votes">${x.votes_count||0} голосів</span></div><div class="stats"><div><div class="label">Ваша ціна</div><div class="value" data-my-value="${x.id}">${mine==null?'—':money(mine)} грн</div></div><div><div class="label">Середня ціна</div><div class="value">${x.votes_count?money(avg)+' грн':'—'}</div></div></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="sliderRow"><span>10</span><input class="priceSlider" data-id="${x.id}" type="range" min="10" max="5000" step="10" value="${value}"><span>5000</span></div><div class="sliderCurrent"><span>Ваша ціна</span><b data-slider-value="${x.id}">${money(value)} грн</b></div><div class="cardActions"><button data-id="${x.id}" data-action="lower">− 10 грн</button><button data-id="${x.id}" data-action="higher">+ 10 грн</button></div>`;prices.appendChild(el)})}
async function savePrice(id,value){value=Math.max(10,Math.min(5000,Math.round(Number(value)/10)*10));try{await api('price_votes?on_conflict=item_id%2Ctelegram_user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({item_id:id,telegram_user_id:visitorId,price:value,updated_at:new Date().toISOString()})});myPrices[id]=value;localStorage.setItem('myPriceVotes',JSON.stringify(myPrices));await loadItems()}catch(e){console.error(e);setStatus('Не вдалося зберегти ціну.',false)}}
prices.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id,x=items.find(i=>i.id===id);if(!x)return;const cur=Number.isFinite(myPrices[id])?myPrices[id]:(x.average_price||10);savePrice(id,cur+(b.dataset.action==='higher'?10:-10))});
prices.addEventListener('input',e=>{const s=e.target.closest('.priceSlider');if(!s)return;const c=s.closest('.card'),id=s.dataset.id,v=Number(s.value);c.querySelector(`[data-slider-value="${id}"]`).textContent=`${money(v)} грн`;c.querySelector(`[data-my-value="${id}"]`).textContent=`${money(v)} грн`});
prices.addEventListener('change',e=>{const s=e.target.closest('.priceSlider');if(s)savePrice(s.dataset.id,s.value)});
$('#addBtn').onclick=()=>modal.showModal();
$('#suggestForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#suggestName').value.trim();if(name.length<2)return;try{await rpc('submit_price_suggestion',{p_text:name,p_telegram_user_id:visitorId});e.target.reset();modal.close();setStatus('Заявку відправлено адміністратору. Після перевірки позиція зʼявиться для голосування.',true)}catch(err){console.error(err);setStatus('Не вдалося відправити заявку.',false)}});
$('#adminBtn').onclick=()=>{if(adminCode){adminPanel.classList.remove('hidden');loadAdminSuggestions();adminPanel.scrollIntoView({behavior:'smooth'})}else adminModal.showModal()};
$('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const code=$('#adminCode').value.trim();try{await rpc('admin_list_price_suggestions',{p_admin_code:code});adminCode=code;sessionStorage.setItem('averagePriceAdminCode',code);adminModal.close();adminPanel.classList.remove('hidden');await loadAdminSuggestions();adminPanel.scrollIntoView({behavior:'smooth'})}catch(err){alert('Невірний код адміністратора')}});
async function loadAdminSuggestions(){if(!adminCode)return;const list=$('#adminList'),empty=$('#adminEmpty');try{const data=await rpc('admin_list_price_suggestions',{p_admin_code:adminCode});list.innerHTML='';empty.classList.toggle('hidden',!!data?.length);(data||[]).forEach(s=>{const el=document.createElement('div');el.className='request';el.innerHTML=`<div><b>${esc(s.text)}</b><div class="requestMeta">Заявка · ${new Date(s.created_at).toLocaleString('uk-UA')}</div></div><div class="requestActions"><button class="accept" data-id="${s.id}">Додати в прайс</button><button class="reject" data-id="${s.id}">Відхилити</button></div>`;list.appendChild(el)})}catch(e){adminCode='';sessionStorage.removeItem('averagePriceAdminCode');adminPanel.classList.add('hidden');alert('Сесія адміністратора завершена.')}}
$('#adminRefresh').onclick=loadAdminSuggestions;
$('#adminList').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.classList.contains('accept'))await rpc('admin_accept_price_suggestion',{p_admin_code:adminCode,p_suggestion_id:b.dataset.id});else await rpc('admin_reject_price_suggestion',{p_admin_code:adminCode,p_suggestion_id:b.dataset.id});await loadAdminSuggestions();await loadItems()}catch(err){alert('Не вдалося виконати дію.')}});
$('#adminAddBtn').onclick=async()=>{const name=$('#adminName').value.trim();if(name.length<2)return;try{await rpc('admin_add_price_item',{p_admin_code:adminCode,p_name:name,p_category:$('#adminCategory').value.trim()||null,p_unit:$('#adminUnit').value.trim()||null});$('#adminName').value='';$('#adminCategory').value='';$('#adminUnit').value='';await loadItems();await loadAdminSuggestions()}catch(e){alert('Не вдалося додати позицію.')}};
search.addEventListener('input',render);
loadItems().catch(e=>{console.error(e);setStatus('Помилка підключення до бази. Перезавантажте сторінку.',false)});
if(adminCode){adminPanel.classList.remove('hidden');loadAdminSuggestions()}
