"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getEstimate} from "../../../../lib/estimate-store";
import {costItemsFromEstimate,calculateInternalCost,type InternalCost} from "../../../../lib/nomenclature-model";
import {getInternalCost,saveInternalCost} from "../../../../lib/internal-cost-store";
import {getPayroll,type PayrollEntry} from "../../../../lib/payroll-store";
import {getObjectConsumption} from "../../../../lib/warehouse-store";
import {consumptionTotal,type StockMovement} from "../../../../lib/warehouse-model";
import "./finance.css";

type ServerFinancials={revenue:string;paid:string;material_cost:string;payroll_cost:string;delivery_cost:string;other_cost:string;profit:string;debt:string};

export default function FinancePage({params}:{params:Promise<{id:string}>}){
 const[id,setId]=useState(""); const[cost,setCost]=useState<InternalCost|null>(null); const[revenue,setRevenue]=useState(0); const[install,setInstall]=useState(0); const[delivery,setDelivery]=useState(0); const[other,setOther]=useState(0); const[paid,setPaid]=useState(0); const[server,setServer]=useState<ServerFinancials|null>(null); const[payroll,setPayroll]=useState<PayrollEntry[]>([]); const[movements,setMovements]=useState<StockMovement[]>([]); const[busy,setBusy]=useState(false); const[message,setMessage]=useState("");
 useEffect(()=>{params.then(async({id})=>{setId(id); const[estimate,saved,entries,warehouse]=await Promise.all([getEstimate(id),getInternalCost(id),getPayroll(id),getObjectConsumption(id)]); setPayroll(entries);setMovements(warehouse); const r=estimate?.total??0; const confirmed=entries.filter(e=>e.status!=="draft").reduce((s,e)=>s+e.amount,0); const labor=saved?.installationCost??confirmed; setRevenue(saved?.revenue??r);setInstall(labor);setDelivery(saved?.deliveryCost??0);setOther(saved?.otherCost??0); if(saved)setCost(saved); else if(estimate)setCost(calculateInternalCost(id,costItemsFromEstimate(estimate.items),r,labor)); try{const res=await fetch(`/api/objects/${id}/financials`,{cache:"no-store"});if(res.ok){const data=await res.json();if(data.ok)setServer(data.financials)}}catch{}})},[params]);
 function recalc(nextInstall=install,nextRevenue=revenue,nextDelivery=delivery,nextOther=other){if(cost)setCost(calculateInternalCost(id,cost.items,nextRevenue,nextInstall,nextDelivery,nextOther))}
 async function write(action:"expense"|"payment",amount:number,category?:string){if(amount<=0)return;setBusy(true);setMessage("");try{const res=await fetch(`/api/objects/${id}/financials`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,amount,category})});if(!res.ok)throw new Error();const data=await res.json();if(!data.ok)throw new Error();const fresh=await fetch(`/api/objects/${id}/financials`,{cache:"no-store"});if(fresh.ok){const next=await fresh.json();if(next.ok)setServer(next.financials)}setMessage(action==="payment"?"Оплату збережено":"Витрату збережено")}catch{setMessage("Сервер недоступний — збережіть після відновлення мережі")}finally{setBusy(false)}}
 async function save(){if(cost)await saveInternalCost(cost)}
 if(!cost)return <main className="finance"><Link href={`/objects/${id}`}>← До об’єкта</Link><h1>Фінанси об’єкта</h1><p>Спочатку створіть клієнтський кошторис.</p></main>;
 const issuedCost=consumptionTotal(movements); const shownMaterialCost=server?Number(server.material_cost):movements.length?issuedCost:cost.materialCost; const shownInstall=server?Number(server.payroll_cost):install; const shownDelivery=server?Number(server.delivery_cost):delivery; const shownOther=server?Number(server.other_cost):other; const shownRevenue=server?Number(server.revenue):cost.revenue; const shownProfit=server?Number(server.profit):shownRevenue-shownMaterialCost-shownInstall-shownDelivery-shownOther; const shownPaid=server?Number(server.paid):paid; const shownDebt=server?Number(server.debt):Math.max(shownRevenue-shownPaid,0);
 return <main className="finance"><Link href={`/objects/${id}`}>← До об’єкта</Link><header><div className="eyebrow">ВНУТРІШНІ ФІНАНСИ</div><h1>Собівартість та прибуток</h1><p>{server?"Дані з сервера":"Офлайн-режим"}</p></header><section className="metrics"><article><span>Виручка</span><strong>{shownRevenue.toLocaleString("uk-UA")} ₴</strong></article><article><span>Матеріали</span><strong>{shownMaterialCost.toLocaleString("uk-UA")} ₴</strong></article><article><span>Собівартість</span><strong>{(shownMaterialCost+shownInstall+shownDelivery+shownOther).toLocaleString("uk-UA")} ₴</strong></article><article><span>Прибуток</span><strong>{shownProfit.toLocaleString("uk-UA")} ₴</strong></article></section><section className="panel"><h2>Розрахунки</h2><div className="line"><span>Отримано від клієнта</span><b>{shownPaid.toLocaleString("uk-UA")} ₴</b></div><div className="line"><span>Залишок до оплати</span><b>{shownDebt.toLocaleString("uk-UA")} ₴</b></div><label>Сума нової оплати<input type="number" min="0" value={paid||""} onChange={e=>setPaid(Number(e.target.value)||0)} /></label><button className="primary" disabled={busy||paid<=0} onClick={()=>write("payment",paid)}>Зберегти оплату</button></section><section className="panel"><h2>Матеріали</h2>{movements.length?movements.map(m=><div className="line" key={m.id}><span>{m.name} · {Math.abs(m.quantity)} {m.unit}</span><b>{(Math.abs(m.quantity)*m.unitCost).toLocaleString("uk-UA")} ₴</b></div>):cost.items.map(item=><div className="line" key={item.sku}><span>{item.name}</span><span>{item.quantity} {item.unit} × {item.unitCost} ₴ = <b>{item.total.toLocaleString("uk-UA")} ₴</b></span></div>)}</section><section className="panel"><h2>Зарплата монтажників</h2>{payroll.length?<>{payroll.map(p=><div className="line" key={p.id}><span>{p.installerName} · {p.status}</span><b>{p.amount.toLocaleString("uk-UA")} ₴</b></div>)}<div className="line"><b>Разом</b><b>{shownInstall.toLocaleString("uk-UA")} ₴</b></div></>:<p>Нарахувань ще немає.</p>}<label>Додатковий монтаж / зарплата<input type="number" value={install} onChange={e=>{const v=Math.max(0,Number(e.target.value)||0);setInstall(v);recalc(v)}} /></label></section><section className="panel"><h2>Інші витрати</h2><label>Доставка<input type="number" value={delivery} onChange={e=>{const v=Math.max(0,Number(e.target.value)||0);setDelivery(v);recalc(install,revenue,v,other)}} /></label><label>Інші витрати<input type="number" value={other} onChange={e=>{const v=Math.max(0,Number(e.target.value)||0);setOther(v);recalc(install,revenue,delivery,v)}} /></label><div className="actions"><button disabled={busy||delivery<=0} onClick={()=>write("expense",delivery,"delivery")}>Зберегти доставку</button><button disabled={busy||other<=0} onClick={()=>write("expense",other,"other")}>Зберегти інші витрати</button><button className="primary" onClick={save}>Зберегти фінанси</button></div>{message&&<p>{message}</p>}</section></main>;
}
