"use client";
import Link from "next/link";import{useEffect,useState}from"react";import{useParams}from"next/navigation";import{getEstimate}from"../../../../lib/estimate-store";import{getInventory}from"../../../../lib/warehouse-inventory";import{createProductionOrderFromEstimate,hasProductionShortage,type ProductionOrder,type ProductionStatus}from"../../../../lib/production-model";import{getProductionOrder,saveProductionOrder}from"../../../../lib/production-store";import{getReservations,reserveForObject,releaseObjectReservation,issueReservedForObject}from"../../../../lib/warehouse-operations";import"./production.css";
const statuses:ProductionStatus[]=["new","processing","ready","issued","completed"];const labels:Record<ProductionStatus,string>={new:"Нове",processing:"У виробництві",ready:"Готово",issued:"Видано",completed:"Завершено"};
export default function ProductionPage(){const params=useParams<{id:string}>();const id=params.id;const[order,setOrder]=useState<ProductionOrder|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[reserved,setReserved]=useState(false);
async function refresh(){setLoading(true);const existing=await getProductionOrder(id);const estimate=await getEstimate(id);const inventory=await getInventory();const reservations=await getReservations();if(existing)setOrder(existing);else if(estimate)setOrder(createProductionOrderFromEstimate(estimate,inventory,reservations));else setOrder(null);setReserved(reservations.some(r=>r.objectId===id&&r.status==="active"));setLoading(false)}useEffect(()=>{void refresh()},[id]);
async function regenerate(){const estimate=await getEstimate(id);if(!estimate)return;const next=createProductionOrderFromEstimate(estimate,await getInventory(),await getReservations());setOrder(next);await saveProductionOrder(next);setMessage("Специфікацію оновлено з актуального кошторису.")}
async function reserve(){if(!order||hasProductionShortage(order))return;try{await reserveForObject(id,order.companyId,order.items.map(x=>({sku:x.sku,quantity:x.quantity,unitCost:x.unitCost})));setReserved(true);setMessage("Матеріали зарезервовано під об’єкт.");await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Не вдалося створити резерв.")}}
async function release(){await releaseObjectReservation(id);setReserved(false);setMessage("Резерв матеріалів скасовано.");await refresh()}
async function issue(){if(!order)return;try{await issueReservedForObject(id);const next={...order,status:"issued" as ProductionStatus,updatedAt:new Date().toISOString()};setOrder(next);await saveProductionOrder(next);setReserved(false);setMessage("Матеріали списано зі складу та видано у виробництво.")}catch(e){setMessage(e instanceof Error?e.message:"Не вдалося списати матеріали.")}}
async function setStatus(status:ProductionStatus){if(!order)return;if(status==="ready"&&hasProductionShortage(order)){setMessage("Неможливо позначити готовим: не вистачає матеріалів.");return}if(status==="issued"){if(order.status!=="ready"){setMessage("Спочатку переведіть виробництво у статус «Готово».");return}return issue()}const next={...order,status,updatedAt:new Date().toISOString()};setOrder(next);await saveProductionOrder(next);setMessage(`Статус: ${labels[status]}`)}
if(loading)return <main className="production-page"><p>Завантаження…</p></main>;if(!order)return <main className="production-page"><h1>Виробництво</h1><p>Спочатку створіть і збережіть кошторис.</p><Link href={`/objects/${id}/estimate`}>Відкрити кошторис</Link></main>;const shortage=hasProductionShortage(order);return <main className="production-page"><header className="production-header"><div><Link href={`/objects/${id}`}>← Об’єкт</Link><h1>Виробниче завдання</h1><p>Специфікація матеріалів для виробництва та комплектації.</p></div><button onClick={()=>void regenerate()}>↻ Оновити</button></header><section className="production-status">{statuses.map(s=><button key={s} className={order.status===s?"active":""} onClick={()=>void setStatus(s)}>{labels[s]}</button>)}</section>{shortage&&<div className="production-alert">⚠️ Є дефіцит матеріалів. Поповніть склад.</div>}{message&&<div className="production-message">{message}</div>}<section className="production-card"><div className="production-table production-head"><span>Матеріал</span><span>Потрібно</span><span>Доступно</span><span>Дефіцит</span><span>Собівартість</span></div>{order.items.map(item=><div className="production-table" key={item.id}><span><b>{item.name}</b><small>{item.sku}</small></span><span>{item.quantity} {item.unit}</span><span>{item.available} {item.unit}</span><span className={item.shortage?"shortage":"ok"}>{item.shortage?`-${item.shortage}`:"✓"}</span><span>{item.totalCost.toFixed(2)} грн</span></div>)}<div className="production-total">Собівартість матеріалів: <b>{order.totalCost.toFixed(2)} грн</b></div></section><div className="production-actions">{!reserved&&!shortage&&order.status!=="issued"&&<button onClick={()=>void reserve()}>🔒 Зарезервувати матеріали</button>}{reserved&&order.status!=="issued"&&<button onClick={()=>void release()}>↩ Скасувати резерв</button>}{reserved&&order.status==="ready"&&<button onClick={()=>void issue()}>📦 Видати та списати зі складу</button>}<Link href={`/objects/${id}/warehouse`}>Склад</Link><Link href={`/objects/${id}/installation`}>Монтаж</Link><Link href={`/objects/${id}/finance`}>Фінанси</Link></div></main>}
