create extension if not exists pgcrypto;

do $$ begin create type user_role as enum ('super_admin','company_owner','admin','manager','estimator','foreman','installer','accountant','warehouse_manager','production_manager','viewer'); exception when duplicate_object then null; end $$;
do $$ begin create type object_status as enum ('lead','measurement','estimate','contract','deposit_paid','production','ready','delivery','installation','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type stock_movement_type as enum ('receipt','issue','transfer','adjustment'); exception when duplicate_object then null; end $$;
do $$ begin create type reservation_status as enum ('active','released','issued'); exception when duplicate_object then null; end $$;
do $$ begin create type production_status as enum ('new','processing','ready','issued','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type payroll_status as enum ('draft','confirmed','paid','cancelled'); exception when duplicate_object then null; end $$;

create table if not exists companies (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists users (id uuid primary key default gen_random_uuid(), telegram_id bigint not null unique, username text, first_name text, last_name text, language_code text, role user_role not null default 'company_owner', company_id uuid not null references companies(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists clients (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, phone text, email text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists objects (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, client_id uuid not null references clients(id) on delete restrict, title text not null, address text not null default '', status object_status not null default 'lead', manager_id uuid references users(id) on delete set null, estimator_id uuid references users(id) on delete set null, foreman_id uuid references users(id) on delete set null, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists drawings (id uuid primary key default gen_random_uuid(), object_id uuid not null unique references objects(id) on delete cascade, company_id uuid not null references companies(id) on delete cascade, version integer not null default 1, payload jsonb not null, created_by uuid references users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists estimate_versions (id uuid primary key default gen_random_uuid(), object_id uuid not null references objects(id) on delete cascade, company_id uuid not null references companies(id) on delete cascade, version integer not null, author_id uuid references users(id) on delete set null, discount numeric(14,2) not null default 0, subtotal numeric(14,2) not null default 0, total numeric(14,2) not null default 0, created_at timestamptz not null default now(), unique(object_id,version));
create table if not exists estimate_items (id uuid primary key default gen_random_uuid(), estimate_version_id uuid not null references estimate_versions(id) on delete cascade, sku text not null, name text not null, unit text not null, quantity numeric(14,3) not null default 0, unit_price numeric(14,2) not null default 0, total numeric(14,2) not null default 0, sort_order integer not null default 0);
create index if not exists idx_estimate_versions_company_object on estimate_versions(company_id,object_id,version desc);
create index if not exists idx_estimate_items_version on estimate_items(estimate_version_id,sort_order);

create table if not exists warehouses (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, is_default boolean not null default false, created_at timestamptz not null default now());
create table if not exists nomenclature (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, sku text not null, name text not null, category text not null, unit text not null, sale_price numeric(14,2) not null default 0, purchase_price numeric(14,2) not null default 0, minimum_stock numeric(14,3) not null default 0, active boolean not null default true, unique(company_id,sku));
create table if not exists stock_items (warehouse_id uuid not null references warehouses(id) on delete cascade, sku text not null, quantity numeric(14,3) not null default 0, unit_cost numeric(14,2) not null default 0, updated_at timestamptz not null default now(), primary key(warehouse_id,sku));
create table if not exists stock_movements (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, warehouse_id uuid not null references warehouses(id) on delete cascade, object_id uuid references objects(id) on delete set null, sku text not null, movement_type stock_movement_type not null, quantity numeric(14,3) not null, unit_cost numeric(14,2) not null default 0, reference_id uuid, created_by uuid references users(id) on delete set null, created_at timestamptz not null default now());
create index if not exists idx_stock_movements_company_created on stock_movements(company_id,created_at desc);
create index if not exists idx_stock_movements_object on stock_movements(object_id,created_at desc);
create table if not exists stock_reservations (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, object_id uuid not null references objects(id) on delete cascade, warehouse_id uuid not null references warehouses(id) on delete cascade, status reservation_status not null default 'active', created_by uuid references users(id) on delete set null, created_at timestamptz not null default now(), released_at timestamptz);
create table if not exists stock_reservation_items (reservation_id uuid not null references stock_reservations(id) on delete cascade, sku text not null, quantity numeric(14,3) not null, unit_cost numeric(14,2) not null default 0, primary key(reservation_id,sku));
create index if not exists idx_reservations_object_status on stock_reservations(company_id,object_id,status);
create table if not exists production_orders (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, object_id uuid not null references objects(id) on delete cascade, warehouse_id uuid references warehouses(id) on delete set null, status production_status not null default 'new', reservation_id uuid references stock_reservations(id) on delete set null, created_by uuid references users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists production_order_items (id uuid primary key default gen_random_uuid(), production_order_id uuid not null references production_orders(id) on delete cascade, sku text not null, quantity numeric(14,3) not null, unit_cost numeric(14,2) not null default 0, created_at timestamptz not null default now());
create index if not exists idx_production_company_object on production_orders(company_id,object_id,created_at desc);

create table if not exists payroll_entries (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, object_id uuid references objects(id) on delete set null, installer_id uuid not null references users(id) on delete restrict, amount numeric(14,2) not null, rule_type text not null, base_value numeric(14,3) not null default 0, status payroll_status not null default 'draft', note text, created_by uuid references users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_payroll_company_object on payroll_entries(company_id,object_id,created_at desc);

create table if not exists object_expenses (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, object_id uuid not null references objects(id) on delete cascade, category text not null, amount numeric(14,2) not null check(amount>=0), note text, created_by uuid references users(id) on delete set null, created_at timestamptz not null default now());
create index if not exists idx_object_expenses_company_object on object_expenses(company_id,object_id,created_at desc);
create table if not exists object_payments (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, object_id uuid not null references objects(id) on delete cascade, amount numeric(14,2) not null check(amount>0), payment_type text not null default 'client_payment', note text, created_by uuid references users(id) on delete set null, created_at timestamptz not null default now());
create index if not exists idx_object_payments_company_object on object_payments(company_id,object_id,created_at desc);

create table if not exists audit_log (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id) on delete cascade, user_id uuid references users(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists idx_users_company on users(company_id);
create index if not exists idx_clients_company on clients(company_id);
create index if not exists idx_objects_company_status on objects(company_id,status);
create index if not exists idx_drawings_company_object on drawings(company_id,object_id);
create index if not exists idx_audit_company_created on audit_log(company_id,created_at desc);