import {NextResponse} from "next/server";
import {getDb,query} from "../../../../../db/client";
import {requireSession} from "../../../../../lib/auth-session";
export const runtime="nodejs";
type Item={sku:string;name:string;unit:string;quantity:number;unitPrice:number;total:number};
type Version={id:string;objectId:string;version:number;createdAt:string;author:string;discount:number;subtotal:number;total:number;items:Item[]};
type Row={id:string;object_id:string;version:number;created_at:string;discount:string;subtotal:string;total:string;author:string|null};
type ItemRow={sku:string;name:string;unit:string;quantity:string;unit_price:string;total:string};
type CleanItem=Item&{sortOrder:number};
const num=(v:string|number)=>Number(v)||0;
async function load(id:string,companyId:string):Promise<Version|null>{const r=await query<Row>(`select ev.id,ev.object_id,ev.version,ev.created_at,ev.discount,ev.subtotal,ev.total,coalesce(u.first_name||' '||u.last_name,u.username,'Користувач') as author from estimate_versions ev left join users u on u.id=ev.author_id where ev.object_id=$1 and ev.company_id=$2 order by ev.version desc limit 1`,[id,companyId]);if(!r.rows[0])return null;const v=r.rows[0];const rows=(await query<ItemRow>(`select sku,name,unit,quantity,unit_price,total from estimate_items where estimate_version_id=$1 order by sort_order,id`,[v.id])).rows;const items:Item[]=rows.map((x:ItemRow)=>({sku:x.sku,name:x.name,unit:x.unit,quantity:num(x.quantity),unitPrice:num(x.unit_price),total:num(x.total)}));return{id:v.id,objectId:v.object_id,version:v.version,createdAt:v.created_at,author:v.author??"Користувач",discount:num(v.discount),subtotal:num(v.subtotal),total:num(v.total),items};}
export async function GET(_req:Request,{params}:{params:Promise<{id:string}>}){try{const{user}=await requireSession();const{id}=await params;const object=await query<{id:string}>(`select id from objects where id=$1 and company_id=$2`,[id,user.company_id]);if(!object.rows[0])return NextResponse.json({ok:false,error:"OBJECT_NOT_FOUND"},{status:404});return NextResponse.json({ok:true,estimate:await load(id,user.company_id)})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error&&e.message==="AUTH_REQUIRED"?"AUTH_REQUIRED":"ESTIMATE_READ_FAILED"},{status:e instanceof Error&&e.message==="AUTH_REQUIRED"?401:500})}}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){try{const{user}=await requireSession();const{id}=await params;const body=await req.json().catch(()=>({}));const object=await query<{id:string}>(`select id from objects where id=$1 and company_id=$2`,[id,user.company_id]);if(!object.rows[0])return NextResponse.json({ok:false,error:"OBJECT_NOT_FOUND"},{status:404});const rawItems:unknown[]=Array.isArray(body?.items)?body.items:[];if(!rawItems.length)return NextResponse.json({ok:false,error:"ITEMS_REQUIRED"},{status:400});const previous=await query<{version:number}>(`select version from estimate_versions where object_id=$1 and company_id=$2 order by version desc limit 1`,[id,user.company_id]);const version=(previous.rows[0]?.version??0)+1;const clean:CleanItem[]=rawItems.map((x:unknown,i:number)=>{const v=(x&&typeof x==="object"?x:{}) as Record<string,unknown>;const quantity=num(v.quantity as string|number),unitPrice=num(v.unitPrice as string|number);return{sku:String(v.sku??""),name:String(v.name??""),unit:String(v.unit??"шт"),quantity,unitPrice,total:Math.round(quantity*unitPrice*100)/100,sortOrder:i}}).filter((x:CleanItem)=>x.sku&&x.quantity>0);const discount=Math.max(0,num(body?.discount));const subtotal=Math.round(clean.reduce((sum:number,item:CleanItem)=>sum+item.total,0)*100)/100;const total=Math.max(0,Math.round((subtotal-discount)*100)/100);const db=await getDb().connect();try{await db.query("begin");const v=(await db.query<{id:string}>(`insert into estimate_versions(object_id,company_id,version,author_id,discount,subtotal,total) values($1,$2,$3,$4,$5,$6,$7) returning id`,[id,user.company_id,version,user.id,discount,subtotal,total])).rows[0];for(const x of clean)await db.query(`insert into estimate_items(estimate_version_id,sku,name,unit,quantity,unit_price,total,sort_order) values($1,$2,$3,$4,$5,$6,$7,$8)`,[v.id,x.sku,x.name,x.unit,x.quantity,x.unitPrice,x.total,x.sortOrder]);await db.query(`update objects set status='estimate',updated_at=now() where id=$1 and company_id=$2`,[id,user.company_id]);await db.query(`insert into audit_log(company_id,user_id,action,entity_type,entity_id,metadata) values($1,$2,'create','estimate',$3,$4::jsonb)`,[user.company_id,user.id,id,JSON.stringify({version,total})]);await db.query("commit")}catch(e){await db.query("rollback");throw e}finally{db.release()}return NextResponse.json({ok:true,estimate:await load(id,user.company_id)},{status:201})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error&&e.message==="AUTH_REQUIRED"?"AUTH_REQUIRED":"ESTIMATE_SAVE_FAILED"},{status:e instanceof Error&&e.message==="AUTH_REQUIRED"?401:500})}}
