"use client";
import{useEffect,useState}from"react";import{getLocalCompany}from"../../lib/auth-model";import{apiClients,apiCreateClient,apiCreateObject,apiObjects}from"../../lib/crm-api";import{listClients,listObjects,saveClient,saveObject,type Client,type ObjectRecord,type ObjectStatus}from"../../lib/crm-model";import"./objects.css";
const labels:Record<ObjectStatus,string>={lead:"Лід",measurement:"Замір",estimate:"Кошторис",contract:"Договір",deposit_paid:"Аванс",production:"Виробництво",ready:"Готово",delivery:"Доставка",installation:"Монтаж",completed:"Завершено",cancelled:"Скасовано"};
export default function ObjectsPage(){const[companyId,setCompanyId]=useState("");const[clients,setClients]=useState<Client[]>([]);const[objects,setObjects]=useState<ObjectRecord[]>([]);const[name,setName]=useState("");const[phone,setPhone]=useState("");const[title,setTitle]=useState("");const[address,setAddress]=useState("");const[selected,setSelected]=useState("");const[status,setStatus]=useState<ObjectStatus>("lead");const[message,setMessage]=useState("");
async function reload(){if(!companyId)return;const localC=listClients(companyId),localO=listObjects(companyId);setClients(localC);setObjects(localO);try{const[c,o]=await Promise.all([apiClients(),apiObjects()]);setClients(c);setObjects(o);c.forEach(saveClient);o.forEach(saveObject)}catch{}}
useEffect(()=>{const sync=()=>setCompanyId(getLocalCompany()?.id??"");sync();window.addEventListener("stelya-auth-ready",sync);return()=>window.removeEventListener("stelya-auth-ready",sync)},[]);useEffect(()=>{void reload()},[companyId]);
async function createClient(){if(!companyId||!name.trim()||!phone.trim())return setMessage("Вкажіть ім’я та телефон клієнта");try{const c=await apiCreateClient({name:name.trim(),phone:phone.trim()});saveClient(c);setName("");setPhone("");setSelected(c.id);setMessage("Клієнта збережено")}catch{const now=new Date().toISOString();const c:Client={id:crypto.randomUUID(),companyId,name:name.trim(),phone:phone.trim(),createdAt:now,updatedAt:now};saveClient(c);setSelected(c.id);setMessage("Збережено офлайн — синхронізуємо пізніше")}await reload()}
async function createObject(){if(!companyId||!selected||!title.trim()||!address.trim())return setMessage("Оберіть клієнта та заповніть назву й адресу");try{const o=await apiCreateObject({clientId:selected,title:title.trim(),address:address.trim(),status});saveObject(o);setTitle("");setAddress("");setMessage("Об’єкт збережено")}catch{const now=new Date().toISOString();saveObject({id:crypto.randomUUID(),companyId,clientId:selected,title:title.trim(),address:address.trim(),status,createdAt:now,updatedAt:now});setTitle("");setAddress("");setMessage("Збережено офлайн — синхронізуємо пізніше")}await reload()}
return <main className="objects-page"><header><div className="eyebrow">СТЕЛЯ OS</div><h1>Об’єкти</h1><p>Клієнти, заміри та робочий статус кожного об’єкта.</p></header><section className="object-grid"><article className="panel"><h2>Новий клієнт</h2><input placeholder="Ім’я клієнта" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Телефон" value={phone} onChange={e=>setPhone(e.target.value)}/><button type="button" onClick={()=>void createClient()}>Додати клієнта</button></article><article className="panel"><h2>Новий об’єкт</h2><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Оберіть клієнта</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select><input placeholder="Назва об’єкта" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Адреса" value={address} onChange={e=>setAddress(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value as ObjectStatus)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button type="button" onClick={()=>void createObject()}>Створити об’єкт</button></article></section>{message&&<div className="object-message">{message}</div>}<section className="panel"><h2>Мої об’єкти <span>{objects.length}</span></h2>{objects.length===0?<p className="empty">Поки немає об’єктів.</p>:<div className="object-list">{objects.map(o=>{const c=clients.find(x=>x.id===o.clientId);return <article className="object-row" key={o.id}><div><strong>{o.title}</strong><span>{c?.name??"Клієнт"} · {o.address}</span></div><b>{labels[o.status]}</b></article>})}</div>}</section></main>}
